# Build stage
FROM node:20-alpine AS build

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy source code
COPY . .

# Build arguments for Azure OpenAI credentials
ARG VITE_AZURE_OPENAI_ENDPOINT
ARG VITE_AZURE_OPENAI_API_KEY
ARG VITE_AZURE_OPENAI_DEPLOYMENT_GPT52
ARG VITE_AZURE_OPENAI_DEPLOYMENT_GPT41
ARG VITE_AZURE_OPENAI_DEPLOYMENT_GPT41MINI

# Set environment variables for build
ENV VITE_AZURE_OPENAI_ENDPOINT=$VITE_AZURE_OPENAI_ENDPOINT
ENV VITE_AZURE_OPENAI_API_KEY=$VITE_AZURE_OPENAI_API_KEY
ENV VITE_AZURE_OPENAI_DEPLOYMENT_GPT52=$VITE_AZURE_OPENAI_DEPLOYMENT_GPT52
ENV VITE_AZURE_OPENAI_DEPLOYMENT_GPT41=$VITE_AZURE_OPENAI_DEPLOYMENT_GPT41
ENV VITE_AZURE_OPENAI_DEPLOYMENT_GPT41MINI=$VITE_AZURE_OPENAI_DEPLOYMENT_GPT41MINI

# Build the app
RUN npm run build

# Production stage
FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci --omit=dev

COPY --from=build /app/dist ./dist
COPY --from=build /app/server ./server

ENV NODE_ENV=production
ENV PORT=80

EXPOSE 80

CMD ["node", "server/index.js"]
