/**
 * Deterministic Bicep emitter — AVM (Azure Verified Modules) aligned.
 *
 * Emits `br/public:avm/res/...` module calls for the networking backbone,
 * private endpoints, and private DNS zones derived from a PhysicalManifest.
 * Output is deterministic: identical manifests yield byte-identical Bicep.
 *
 * Scope: the golden-scenario network fabric (VNets, subnets, Azure Firewall,
 * private DNS zones, private endpoints). Workload service resources are
 * intentionally represented as private-endpoint targets only in the MVP.
 */
import type { PhysicalManifest } from "../manifest/schema.js";
import { analyzeIpam } from "../ipam/engine.js";
import { privateLinkFor } from "../manifest/privateLink.js";

/** Pinned AVM module versions for reproducible builds. */
const AVM = {
  vnet: "br/public:avm/res/network/virtual-network:0.5.1",
  firewall: "br/public:avm/res/network/azure-firewall:0.6.0",
  privateDnsZone: "br/public:avm/res/network/private-dns-zone:0.7.0",
  privateEndpoint: "br/public:avm/res/network/private-endpoint:0.10.1",
} as const;

/** Convert an arbitrary name into a safe Bicep symbolic identifier. */
function symbol(prefix: string, name: string): string {
  const cleaned = name.replace(/[^a-zA-Z0-9]/g, "_");
  return `${prefix}_${cleaned}`;
}

export function generateBicep(manifest: PhysicalManifest): string {
  const ipam = analyzeIpam(manifest);
  const lines: string[] = [];

  lines.push(
    "// Generated by AADB Physical Architecture Studio (Technical Preview).",
    "// AVM-aligned. Deterministic output derived from the physical manifest.",
    "// DO NOT hand-edit: regenerate from the manifest instead.",
    "",
    "targetScope = 'resourceGroup'",
    "",
    `@description('Primary Azure region for all resources.')`,
    `param location string = '${manifest.regions.primary}'`,
    "",
  );

  // --- Virtual networks + subnets -----------------------------------------
  for (const lz of manifest.landingZones) {
    for (const vnet of lz.vnets) {
      const sym = symbol("vnet", vnet.name);
      lines.push(
        `// ${lz.kind} landing zone: ${lz.name}`,
        `module ${sym} '${AVM.vnet}' = {`,
        `  name: 'deploy-${vnet.name}'`,
        `  params: {`,
        `    name: '${vnet.name}'`,
        `    location: location`,
        `    addressPrefixes: [`,
        ...vnet.addressSpace.map((a) => `      '${a}'`),
        `    ]`,
        `    subnets: [`,
      );
      for (const subnet of vnet.subnets) {
        lines.push(
          `      {`,
          `        name: '${subnet.name}'`,
          `        addressPrefix: '${subnet.addressPrefix}'`,
        );
        if (subnet.delegation !== "none") {
          lines.push(`        delegation: '${subnet.delegation}'`);
        }
        lines.push(`      }`);
      }
      lines.push(`    ]`, `  }`, `}`, "");
    }
  }

  // --- Private DNS zones ---------------------------------------------------
  for (const zone of manifest.privateDnsZones) {
    const sym = symbol("pdns", zone.zone);
    lines.push(
      `module ${sym} '${AVM.privateDnsZone}' = {`,
      `  name: 'deploy-${zone.zone}'`,
      `  params: {`,
      `    name: '${zone.zone}'`,
      `    virtualNetworkLinks: [`,
      ...zone.linkedVnets.map(
        (v) =>
          `      { virtualNetworkResourceId: ${symbol("vnet", v)}.outputs.resourceId }`,
      ),
      `    ]`,
      `  }`,
      `}`,
      "",
    );
  }

  // --- Private endpoints (with deterministic static IPs) -------------------
  for (const lz of manifest.landingZones) {
    const serviceKindByName = new Map(lz.services.map((s) => [s.name, s.kind]));
    for (const vnet of lz.vnets) {
      for (const pe of lz.privateEndpoints) {
        const alloc = ipam.privateEndpoints.find((p) => p.name === pe.name);
        if (!alloc) continue;
        const subnetInVnet = vnet.subnets.some((s) => s.name === pe.subnet);
        if (!subnetInVnet) continue;
        const kind = serviceKindByName.get(pe.service);
        const link = privateLinkFor(kind ?? "keyVault");
        const sym = symbol("pe", pe.name);
        lines.push(
          `module ${sym} '${AVM.privateEndpoint}' = {`,
          `  name: 'deploy-${pe.name}'`,
          `  params: {`,
          `    name: '${pe.name}'`,
          `    location: location`,
          `    subnetResourceId: '\${${symbol("vnet", vnet.name)}.outputs.resourceId}/subnets/${pe.subnet}'`,
          `    privateLinkServiceConnections: [`,
          `      {`,
          `        name: '${pe.name}-connection'`,
          `        properties: {`,
          `          // privateLinkServiceId is supplied when the workload service is deployed`,
          `          privateLinkServiceId: '<${pe.service}-resource-id>'`,
          `          groupIds: [ '${link.groupId}' ]`,
          `        }`,
          `      }`,
          `    ]`,
          `    // Deterministically allocated by the IPAM engine`,
          `    ipConfigurations: [`,
          `      {`,
          `        name: '${pe.name}-ipconfig'`,
          `        properties: {`,
          `          groupId: '${link.groupId}'`,
          `          memberName: '${link.memberName}'`,
          `          privateIPAddress: '${alloc.allocatedIp}'`,
          `        }`,
          `      }`,
          `    ]`,
          `    privateDnsZoneGroup: {`,
          `      privateDnsZoneGroupConfigs: [`,
          `        { privateDnsZoneResourceId: ${symbol("pdns", pe.privateDnsZone)}.outputs.resourceId }`,
          `      ]`,
          `    }`,
          `  }`,
          `}`,
          "",
        );
      }
    }
  }

  return lines.join("\n");
}
