/**
 * Management group hierarchy emitter (Bicep, tenant scope).
 *
 * ALZ governs subscriptions through a management group hierarchy so that Azure
 * Policy is inherited consistently:
 *
 *   Tenant root
 *   └── Intermediate root (e.g. "alz")
 *       ├── Platform ── Management / Identity / Connectivity / Security
 *       ├── Landing zones ── Corp / Online
 *       ├── Sandbox
 *       └── Decommissioned
 *
 * Management groups are tenant-scoped, so they are emitted as a SEPARATE
 * deployment from the resource-group-scoped network template.
 *
 * For production, prefer the ALZ IaC Accelerator / AVM platform landing zone
 * modules (https://aka.ms/alz/accelerator), which also apply the policy
 * assignments. This emitter creates the hierarchy only.
 */
import type { PhysicalManifest } from "../manifest/schema.js";

const MG_API = "2023-04-01";

/** Convert an arbitrary name into a safe Bicep symbolic identifier. */
function symbol(prefix: string, name: string): string {
  return `${prefix}_${name.replace(/[^a-zA-Z0-9]/g, "_")}`;
}

/** Lowercase, hyphenated id used as the management group name. */
function mgId(root: string, name: string): string {
  return `${root}-${name}`.toLowerCase().replace(/[^a-z0-9-]/g, "-");
}

/**
 * Emit the ALZ management group hierarchy. Returns an empty string when the
 * manifest declares no hierarchy.
 */
export function generateManagementGroupsBicep(manifest: PhysicalManifest): string {
  const mg = manifest.managementGroups;
  if (!mg) return "";

  const root = mg.intermediateRoot;
  const lines: string[] = [];

  lines.push(
    "// Generated by AADB Physical Architecture Studio (Technical Preview).",
    "// ALZ management group hierarchy. Deploy at tenant scope:",
    "//   az deployment tenant create --location <region> --template-file managementGroups.bicep",
    "// DO NOT hand-edit: regenerate from the manifest instead.",
    "",
    "targetScope = 'tenant'",
    "",
    `// Intermediate root management group`,
    `resource ${symbol("mg", root)} 'Microsoft.Management/managementGroups@${MG_API}' = {`,
    `  name: '${root}'`,
    `  properties: {`,
    `    displayName: '${root}'`,
    `  }`,
    `}`,
    "",
  );

  /** Emit a child management group parented to another. */
  const child = (name: string, parentSymbol: string, parentComment: string) => {
    const id = mgId(root, name);
    lines.push(
      `// ${parentComment}`,
      `resource ${symbol("mg", id)} 'Microsoft.Management/managementGroups@${MG_API}' = {`,
      `  name: '${id}'`,
      `  properties: {`,
      `    displayName: '${name}'`,
      `    details: {`,
      `      parent: {`,
      `        id: ${parentSymbol}.id`,
      `      }`,
      `    }`,
      `  }`,
      `}`,
      "",
    );
    return symbol("mg", id);
  };

  // Platform + its four subscriptions' management groups.
  const platformSym = child("Platform", symbol("mg", root), "Platform landing zone");
  for (const p of mg.platform) {
    child(p, platformSym, `Platform subscription: ${p}`);
  }

  // Landing zones + archetypes.
  const lzSym = child("Landing zones", symbol("mg", root), "Application landing zones");
  for (const a of mg.landingZones) {
    child(a, lzSym, `Application landing zone archetype: ${a}`);
  }

  if (mg.sandbox) child("Sandbox", symbol("mg", root), "Sandbox");
  if (mg.decommissioned) child("Decommissioned", symbol("mg", root), "Decommissioned");

  return lines.join("\n");
}

/** Emit the same hierarchy as Terraform. */
export function generateManagementGroupsTerraform(manifest: PhysicalManifest): string {
  const mg = manifest.managementGroups;
  if (!mg) return "";

  const root = mg.intermediateRoot;
  const ident = (s: string) => s.replace(/[^a-zA-Z0-9]/g, "_");
  const lines: string[] = [];

  lines.push(
    "# Generated by AADB Physical Architecture Studio (Technical Preview).",
    "# ALZ management group hierarchy.",
    "# DO NOT hand-edit: regenerate from the manifest instead.",
    "",
    `resource "azurerm_management_group" "${ident(root)}" {`,
    `  display_name = "${root}"`,
    `  name         = "${root}"`,
    `}`,
    "",
  );

  const child = (name: string, parentIdent: string, comment: string) => {
    const id = mgId(root, name);
    lines.push(
      `# ${comment}`,
      `resource "azurerm_management_group" "${ident(id)}" {`,
      `  display_name               = "${name}"`,
      `  name                       = "${id}"`,
      `  parent_management_group_id = azurerm_management_group.${parentIdent}.id`,
      `}`,
      "",
    );
    return ident(id);
  };

  const platformIdent = child("Platform", ident(root), "Platform landing zone");
  for (const p of mg.platform) child(p, platformIdent, `Platform subscription: ${p}`);

  const lzIdent = child("Landing zones", ident(root), "Application landing zones");
  for (const a of mg.landingZones) child(a, lzIdent, `Application landing zone archetype: ${a}`);

  if (mg.sandbox) child("Sandbox", ident(root), "Sandbox");
  if (mg.decommissioned) child("Decommissioned", ident(root), "Decommissioned");

  return lines.join("\n");
}
