/**
 * Deterministic Terraform emitter — Azure Verified Modules aligned.
 *
 * Emits `Azure/avm-res-network-*` module blocks derived from a PhysicalManifest.
 * Output is deterministic: identical manifests yield byte-identical HCL.
 *
 * Scope mirrors the Bicep emitter: VNets/subnets, private DNS zones, and private
 * endpoints with the same deterministic static IPs from the IPAM engine.
 */
import type { PhysicalManifest } from "../manifest/schema.js";
import { analyzeIpam } from "../ipam/engine.js";
import { privateLinkFor } from "../manifest/privateLink.js";

/** Pinned AVM Terraform module sources/versions for reproducible builds. */
const AVM = {
  vnet: { source: "Azure/avm-res-network-virtualnetwork/azurerm", version: "0.8.1" },
  privateDnsZone: { source: "Azure/avm-res-network-privatednszone/azurerm", version: "0.3.3" },
  privateEndpoint: { source: "Azure/avm-res-network-privateendpoint/azurerm", version: "0.2.0" },
} as const;

/** Convert an arbitrary name into a safe Terraform identifier. */
function ident(name: string): string {
  return name.replace(/[^a-zA-Z0-9]/g, "_");
}

export function generateTerraform(manifest: PhysicalManifest): string {
  const ipam = analyzeIpam(manifest);
  const lines: string[] = [];

  lines.push(
    "# Generated by AADB Physical Architecture Studio (Technical Preview).",
    "# AVM-aligned. Deterministic output derived from the physical manifest.",
    "# DO NOT hand-edit: regenerate from the manifest instead.",
    "",
    "terraform {",
    "  required_providers {",
    "    azurerm = {",
    '      source  = "hashicorp/azurerm"',
    '      version = "~> 4.0"',
    "    }",
    "  }",
    "}",
    "",
    'variable "location" {',
    "  type    = string",
    `  default = "${manifest.regions.primary}"`,
    "}",
    "",
    'variable "resource_group_name" {',
    "  type = string",
    "}",
    "",
  );

  // --- Virtual networks + subnets -----------------------------------------
  for (const lz of manifest.landingZones) {
    for (const vnet of lz.vnets) {
      const id = ident(vnet.name);
      lines.push(
        `# ${lz.kind} landing zone: ${lz.name}`,
        `module "vnet_${id}" {`,
        `  source  = "${AVM.vnet.source}"`,
        `  version = "${AVM.vnet.version}"`,
        "",
        `  name                = "${vnet.name}"`,
        `  location            = var.location`,
        `  resource_group_name = var.resource_group_name`,
        `  address_space       = [${vnet.addressSpace.map((a) => `"${a}"`).join(", ")}]`,
        "",
        `  subnets = {`,
      );
      for (const subnet of vnet.subnets) {
        lines.push(
          `    ${ident(subnet.name)} = {`,
          `      name             = "${subnet.name}"`,
          `      address_prefixes = ["${subnet.addressPrefix}"]`,
        );
        if (subnet.delegation !== "none") {
          lines.push(
            `      delegation = [{`,
            `        name = "${ident(subnet.name)}-delegation"`,
            `        service_delegation = {`,
            `          name = "${subnet.delegation}"`,
            `        }`,
            `      }]`,
          );
        }
        lines.push(`    }`);
      }
      lines.push(`  }`, `}`, "");
    }
  }

  // --- Private DNS zones ---------------------------------------------------
  for (const zone of manifest.privateDnsZones) {
    const id = ident(zone.zone);
    lines.push(
      `module "pdns_${id}" {`,
      `  source  = "${AVM.privateDnsZone.source}"`,
      `  version = "${AVM.privateDnsZone.version}"`,
      "",
      `  domain_name         = "${zone.zone}"`,
      `  resource_group_name = var.resource_group_name`,
      "",
      `  virtual_network_links = {`,
      ...zone.linkedVnets.map(
        (v) =>
          `    ${ident(v)} = { vnetlinkname = "${v}-link", vnetid = module.vnet_${ident(v)}.resource_id }`,
      ),
      `  }`,
      `}`,
      "",
    );
  }

  // --- Private endpoints (deterministic static IPs) ------------------------
  for (const lz of manifest.landingZones) {
    const serviceKindByName = new Map(lz.services.map((s) => [s.name, s.kind]));
    for (const vnet of lz.vnets) {
      for (const pe of lz.privateEndpoints) {
        const alloc = ipam.privateEndpoints.find((p) => p.name === pe.name);
        if (!alloc) continue;
        if (!vnet.subnets.some((s) => s.name === pe.subnet)) continue;
        const kind = serviceKindByName.get(pe.service);
        const link = privateLinkFor(kind ?? "keyVault");
        const id = ident(pe.name);
        lines.push(
          `module "pe_${id}" {`,
          `  source  = "${AVM.privateEndpoint.source}"`,
          `  version = "${AVM.privateEndpoint.version}"`,
          "",
          `  name                = "${pe.name}"`,
          `  location            = var.location`,
          `  resource_group_name = var.resource_group_name`,
          `  subnet_resource_id  = module.vnet_${ident(vnet.name)}.subnets["${ident(pe.subnet)}"].resource_id`,
          `  subresource_names   = ["${link.groupId}"]`,
          "",
          `  # Deterministically allocated by the IPAM engine`,
          `  private_ip_address = "${alloc.allocatedIp}"`,
          "",
          `  private_dns_zone_group = {`,
          `    name                 = "${pe.name}-dns"`,
          `    private_dns_zone_ids = [module.pdns_${ident(pe.privateDnsZone)}.resource_id]`,
          `  }`,
          `}`,
          "",
        );
      }
    }
  }

  return lines.join("\n");
}
